name: 'Create contracts release file'
description: 'Generates release.txt from a given repo with all the smart contract artifacts.'
inputs:
  target-path:
    description: 'Path to search for the artifacts list.'
    required: true
    default: 'contracts/target/release'
runs:
  using: "composite"
  steps:
    - name: Get Version Tag
      shell: bash
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Test
      shell: bash
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: Check TARGET_DIRECTORY
      shell: bash
      run: |
        if [ -z "${{ inputs.target-path }}" ]
        then
          echo "TARGET_DIRECTORY=contracts/target/release" >> $GITHUB_ENV
        else
          echo "TARGET_DIRECTORY=${{ inputs.target-path }}" >> $GITHUB_ENV
        fi
    - name: Generate and push release artifacts
      shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        date > release.txt
        find ${{ inputs.target-path }}  -print >> sclib-release.txt
        git add sclib-release.txt
        git commit -m "Generate SC lib release file"
        git tag ${{ env.RELEASE_VERSION }}+scdist
        git push origin ${{ env.RELEASE_VERSION }}+scdist